Repository Zoo-Money/ZooMoney_FrontEnd, pull requests merged in 2025-03, with the labels that each got.

#4 [feat]: header 생성(#1)
  src/common/Header.css
  src/common/Header.jsx
Labels: feat, 박은수

#9 [feat]: 웹앱 화면 크기 설정 및 테스트 페이지 (#3)
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/common/Footer.css
  src/common/Footer.jsx
  src/images/rabbit01.png
  src/stock/StockBegin.css
  src/stock/StockBegin.jsx
Labels: feat, 박은수

#13 [feat]: 증권 info 페이지 개발 (#10)
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/common/Footer.css
  src/common/Footer.jsx
  src/common/Header.css
  src/common/Header.jsx
  src/images/rabbit01.png
  src/stock/StockBegin.css
  src/stock/StockBegin.jsx
  src/stock/StockInfo.css
  src/stock/StockInfo.jsx
Labels: feat, 박은수

#23 카드메인페이지 화면 개발(#21)
  src/card/CardHeader.css
  src/card/CardMain.css
  src/card/CardMain.jsx
  src/card/CardMainHeader.jsx
  src/images/bear01.png
  src/images/bell.svg
  src/images/daily.png
  src/images/moneyplan.png
  src/images/pattern.png
  src/images/quiz.png
Labels: ✅ feat, 김용범

#24 [Feat]:뉴스정보 페이지 생성(#5)
  package-lock.json
  package.json
  src/App.js
  src/Stock/StockModal.jsx
  src/Stock/StockNews.jsx
  src/Stock/imgSearching.js
  src/Stock/stockModal.css
  src/Stock/stockNews.css
Labels: ✅ feat, 정재윤

#26 [feat]: 알림 API 기능 / 저금통 생성 기능 개발 (#15 / #20)
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/account/AccountABI.json
  src/account/AccountBurn.jsx
  src/account/AccountContract.sol
  src/account/AccountMint.jsx
  src/account/AccountService.jsx
  src/account/AccountTest.jsx
  src/account/NotifyTest.jsx
Labels: ✅ feat, 전운종

#27 [feat]: Router설정 (#25)
  src/router/Routers.jsx
  src/router/StockRouter.jsx
Labels: ✅ feat, 정재윤

#30 [feat]: 마이페이지개발(#22)
  src/common/MyPage.jsx
  src/common/Mypage.css
  src/images/bear03.png
Labels: ✅ feat, 박은수
