Repository Zoo-Money/ZooMoney_FrontEnd, pull requests merged in 2025-03, with the labels that each got.

#7 [fix]: 의존성 추가 및 오타 수정
  package-lock.json
  package.json
  src/account/AccountMint.jsx
  src/card/CardMain.jsx
  src/card/CardService.jsx
  src/parent/ContractWrite.jsx
  src/parent/ContractWriteChild.jsx
  src/quiz/QuizQuiz.jsx
  src/router/AccountRouter.jsx
Labels: 🛠️ fix, 전운종

#9 [fix]: header, app css 수정 (#8)
  src/App.css
  src/card/CardHeader.css
  src/common/Header.css
  src/common/Header.jsx
Labels: 🛠️ fix, 박은수

#11 [fix]: header css 수정(#10)
  src/common/Header.css
Labels: 🛠️ fix, 박은수

#14 [feat]: 퀴즈 문제 / 결과 페이지 개발 (#3)
  src/images/quiz/giraffe_main.png
  src/quiz/QuizEnd.jsx
  src/quiz/QuizFailure.jsx
  src/quiz/QuizLoading.jsx
  src/quiz/QuizMain.jsx
  src/quiz/QuizQuiz.jsx
  src/quiz/QuizSuccess.jsx
Labels: ✅ feat, 강은영

#19 [fix]: stockInfo, stockInfoDetail 수정(#18)
  src/stock/StockInfo.css
  src/stock/StockInfo.jsx
  src/stock/StockInfoDetail.css
  src/stock/StockInfoDetail.jsx
Labels: 🛠️ fix, 박은수

#20 [feat]: 저금통 조회 화면 개발 (#2)
  src/App.css
  src/account/AccountBurn.js
  src/account/AccountClose.jsx
  src/account/AccountCreate.jsx
  src/account/AccountDetail.jsx
  src/account/AccountInsert.jsx
  src/account/AccountMain.jsx
  src/account/css/AccountClose.css
  src/account/css/AccountCreate.css
  src/account/css/AccountDetail.css
  src/account/css/AccountInsert.css
  src/account/css/AccountMain.css
  src/account/resources/AccountABI.json
  src/account/resources/AccountContract.sol
  src/account/resources/AccountService.js
  src/account/resources/NotifyTest.jsx
  src/card/CardABI.json
  src/card/CardContract.sol
  src/images/ether.png
  src/images/pig02.png
  src/router/AccountRouter.jsx
  src/router/NotifyRouter.jsx
  src/router/StockRouter.jsx
Labels: ✅ feat, 전운종

#21 [feat]: 거래내역조회 화면 개발(#12)
  src/card/CardHistory.css
  src/card/CardHistory.jsx
Labels: ✅ feat, 박은수

#23 [feat]: 모의투자종목 상세페이지 (회사설명) /#17
  src/stock/CompanyInfo.css
  src/stock/CompanyInfo.jsx
  src/stock/StockList.css
  src/stock/StockList.jsx
Labels: ✅ feat, 정홍택

#24 [feat]: 출석체크 페이지 개발 (#16)
  src/daily/DailyEnd.jsx
  src/daily/DailyMain.jsx
  src/daily/dailyEnd.css
  src/daily/dailyMain.css
  src/images/daily/giraffe_daily.png
  src/images/daily/giraffe_end.png
  src/router/DailyRouter.jsx
  src/router/Routers.jsx
Labels: ✅ feat, 강은영

#25 [Feat]:용돈계획관련 기능(#5)
  package-lock.json
  package.json
  src/images/deer2.png
  src/moneyPlan/ContentInput.jsx
  src/moneyPlan/InputComponent.jsx
  src/moneyPlan/PlanChart.jsx
  src/moneyPlan/PlanComplete.jsx
  src/moneyPlan/PlanMain.jsx
  src/moneyPlan/PlanWrite.jsx
  src/moneyPlan/SelectChart.jsx
  src/moneyPlan/moneyPlan.css
  src/moneyPlan/planCommon.js
  src/moneyPlan/planMain.css
  src/router/MoneyPlanRouter.jsx
  src/router/Routers.jsx
Labels: ✅ feat, 정재윤

#30 [feat]:모의투자 랭킹 결과 페이지 생성 (#26)
  src/images/bronze.png
  src/images/gold.png
  src/images/rabbit06.png
  src/images/rabbit07.png
  src/images/silver.png
  src/router/StockRouter.jsx
  src/stock/RankList.jsx
  src/stock/StockRankDetail.jsx
  src/stock/StockRankResult.jsx
  src/stock/stockRankDetail.css
  src/stock/stockRankResult.css
Labels: ✅ feat, 정재윤

#33 [feat]:부모용돈계획확인페이지(#32)
  src/parent/MoneyPlanConfirm.jsx
  src/router/MoneyPlanRouter.jsx
Labels: ✅ feat, 정재윤

#35 [feat]:로그인화면(#34)
  src/images/bear04.png
  src/images/bear05.png
  src/member/Login.jsx
  src/member/SignUp.jsx
  src/member/login.css
  src/router/MemberRouter.jsx
  src/router/Routers.jsx
Labels: ✅ feat, 정재윤

#36 [feat]: 모의투자종목 상세 페이지 개발 #22
  src/stock/CompanyInfo.css
  src/stock/CompanyInfo.jsx
  src/stock/StockDetail.css
  src/stock/StockDetail.jsx
  src/stock/StockNews.jsx
  src/stock/stockNews.css
Labels: ✅ feat, 박은수

#39 [Feat]:모의투자 모의투자 랭킹 히스토리 (#31)
  src/images/rabbit05.png
  src/member/Login.jsx
  src/router/StockRouter.jsx
  src/stock/StockHistory.jsx
  src/stock/StockHistoryDetail.jsx
  src/stock/stockHistory.css
  src/stock/stockHistoryDetail.css
Labels: ✅ feat, 정재윤

#41 [feat] : 퀴즈 메인 페이지 개발 (#15)
  src/daily/DailyEnd.jsx
  src/daily/DailyMain.jsx
  src/daily/dailyEnd.css
  src/daily/dailyMain.css
  src/images/quiz/empty_stamp.avif
  src/images/quiz/o_stamp.png
  src/images/quiz/x_stamp.png
  src/quiz/QuizEnd.jsx
  src/quiz/QuizFailure.jsx
  src/quiz/QuizLoading.jsx
  src/quiz/QuizMain.jsx
  src/quiz/QuizQuiz.jsx
  src/quiz/QuizSuccess.jsx
  src/quiz/quizFailure.css
  src/quiz/quizLoading.css
  src/quiz/quizMain.css
  src/quiz/quizQuiz.css
  src/quiz/quizSuccess.css
Labels: ✅ feat, 강은영

#45 [feat]:모의투자메인페이지생성(#40)
  src/router/StockRouter.jsx
  src/stock/StockMain.jsx
  src/stock/stockMain.css
Labels: ✅ feat, 정재윤

#46 [feat]: 나의 투자내역 상세보기 화면 개발(#13)
  src/stock/MyStockProfit.css
  src/stock/MyStockProfit.jsx
Labels: ✅ feat, 박은수

#47 [feat]: 저금통 기능 개발 (#2)
  package-lock.json
  package.json
  src/App.js
  src/account/AccountCreate.jsx
  src/account/AccountInsert.jsx
  src/account/resources/NotifyTest.jsx
Labels: ✅ feat, 전운종

#48 [fix]: 퀴즈 메인 페이지 스탬프 수정(#44)
  src/quiz/quizMain.css
Labels: 🛠️ fix, 강은영

#49 [feat] 자녀 소비패턴 화면 개발(#27)
  src/card/CardConsumeChart.css
  src/card/CardConsumeChart.jsx
  src/card/CardHistory.jsx
  src/card/CardMain.css
  src/card/CardMain.jsx
  src/card/CardModify.jsx
  src/card/patternCommon.js
  src/router/CardRouter.jsx
Labels: ✅ feat, 김용범

#54 [feat]:부모로그인필터생성(#53)
  src/member/Login.jsx
Labels: ✅ feat, 정재윤

#58 [Feat] 주식 매수 페이지 생성 (#57)
  src/images/rabbit04.png
  src/router/StockRouter.jsx
  src/stock/StockBuy.jsx
  src/stock/StockBuyDone.jsx
  src/stock/css/stockBuy.css
Labels: ✅ feat, 정재윤

#59 [fix] Login img css 수정(#55)
  src/member/Login.jsx
  src/member/login.css
Labels: 🛠️ fix, 강은영

#61 [Fix]:용돈계획 css 수정 및 로그인 css 수정 (#56)
  src/member/Login.jsx
  src/member/login.css
  src/moneyPlan/InputComponent.jsx
  src/moneyPlan/PlanChart.jsx
  src/moneyPlan/PlanComplete.jsx
  src/moneyPlan/PlanMain.jsx
  src/moneyPlan/PlanWrite.jsx
  src/moneyPlan/SelectChart.jsx
  src/moneyPlan/css/moneyPlan.css
  src/moneyPlan/resource/planCommon.js
  src/router/MoneyPlanRouter.jsx
Labels: 🛠️ fix, 정재윤

#65 [fix]: 요청 data type 수정(#64)
  src/card/CardHistory.jsx
  src/card/css/CardHistory.css
  src/common/MyPage.jsx
  src/common/Mypage.css
Labels: 🛠️ fix, 박은수

#66 [fix] Card 관련 화면 css 수정(#52)
  src/card/CardConsumeChart.jsx
  src/card/CardCreate.jsx
  src/card/CardModify.jsx
  src/card/CardService.jsx
  src/card/css/CardConsumeChart.css
  src/card/css/CardCreate.css
  src/card/css/CardModify.css
Labels: 🛠️ fix, 김용범

#70 [feat]: 종목 페이지&매수 페이지 연동(#67)
  src/stock/StockBuy.jsx
  src/stock/StockDetail.jsx
  src/stock/css/StockDetail.css
Labels: ✅ feat, 박은수

#73 [fix]: 주식 종목 리스트 페이지 css 수정(#72)
  src/stock/StockList.jsx
  src/stock/css/StockList.css
Labels: 🛠️ fix, 박은수

#75 [fix]: main으로 가기 버튼/CSS/스크롤 수정 (#60)
  src/daily/DailyEnd.jsx
  src/daily/DailyMain.jsx
  src/daily/dailyEnd.css
  src/daily/dailyMain.css
  src/quiz/QuizFailure.jsx
  src/quiz/QuizMain.jsx
  src/quiz/QuizSuccess.jsx
  src/quiz/css/quizEnd.css
  src/quiz/css/quizFailure.css
  src/quiz/css/quizMain.css
  src/quiz/css/quizQuiz.css
  src/quiz/css/quizSuccess.css
Labels: 🛠️ fix, 강은영

#77 [fix]: 폴더 구조 정리 및 공통 요소 수정
  src/contract/ContractDetail.jsx
  src/contract/ContractSelect.jsx
  src/contract/ContractWrite.jsx
  src/contract/ContractWriteChild.jsx
  src/contract/MoneyContractManage.jsx
  src/contract/css/contractDetail.css
  src/contract/css/contractSelect.css
  src/contract/css/contractWrite.css
  src/contract/css/contractWriteChild.css
  src/contract/css/moneyContractManage.css
  src/member/Login.jsx
  src/member/Main.jsx
  src/parent/ChildEventSend.jsx
  src/parent/MoneyPlanConfirm.jsx
  src/parent/ParentAccount.jsx
  src/parent/ParentMain.jsx
  src/parent/css/parentMain.css
  src/router/AccountRouter.jsx
  src/router/ContractRouter.jsx
  src/router/MoneyPlanRouter.jsx
  src/router/ParentRouter.jsx
  src/router/Routers.jsx
Labels: 🛠️ fix, 전운종

#80 [fix]: 출석체크 오류 수정 (#76)
  src/daily/DailyMain.jsx
Labels: 🛠️ fix, 강은영

#82 [fix]:main css 수정(#69)
  src/member/Main.css
  src/member/Main.jsx
Labels: 🛠️ fix, 정재윤

#83 [fix]: 퀴즈 페이지 로그인 세션 적용 (#81)
  src/quiz/QuizEnd.jsx
  src/quiz/QuizFailure.jsx
  src/quiz/QuizMain.jsx
  src/quiz/QuizQuiz.jsx
  src/quiz/QuizSuccess.jsx
  src/router/ParentRouter.jsx
Labels: 🛠️ fix, 강은영

#85 [fix]:main css 수정 및 코드정리(#84)
  src/member/Main.css
  src/member/Main.jsx
Labels: 🛠️ fix, 정재윤

#86 [Feat]:모의투자 거래 내역 조회 기능 생성(#62)
  src/stock/StockHistory.jsx
  src/stock/StockHistoryDetail.jsx
  src/stock/css/stockHistoryDetail.css
Labels: ✅ feat, 정재윤

#91 [fix]:용돈계획저장수정(#90)
  src/moneyPlan/PlanWrite.jsx
Labels: 🛠️ fix, 정재윤

#93 [feat]: 사용자 참여 여부에 따라 다른 페이지 보여주기(#74)
  src/common/Footer.jsx
  src/router/StockRouter.jsx
  src/stock/StockBegin.jsx
  src/stock/StockInfoDetail.jsx
  src/stock/StockMain.jsx
  src/stock/StockStart.jsx
  src/stock/css/StockBegin.css
  src/stock/css/stockMain.css
Labels: ✅ feat, 박은수

#95 [fix] : 소비패턴 조회 수정(#92)
  src/card/CardConsumeChart.jsx
Labels: 🛠️ fix, 김용범

#99 [fix]: 부모-자식소비내역 확인 페이지 수정 (#87)
  src/parent/CardConsumeChartParent.jsx
Labels: 🛠️ fix, 강은영

#104 [fix] : cardHistroy.jsx 수정(#103)
  src/card/CardHistory.jsx
Labels: 🛠️ fix, 김용범

#105 [feat]: 투자 메인, 내주식 손익 페이지 개발(#94)
  src/stock/StockMain.jsx
  src/stock/css/stockMain.css
Labels: ✅ feat, 박은수

#107 [fix]: stockInfoDetail 예외처리(#106)
  src/stock/StockInfoDetail.jsx
  src/stock/css/StockInfo.css
  src/stock/css/StockInfoDetail.css
Labels: 🛠️ fix, 박은수

#109 [fix]: 불필요 코드 정리 및 알림 로직 수정
  src/card/CardConsumeChart.jsx
  src/contract/ContractWrite.jsx
  src/contract/ContractWriteChild.jsx
  src/member/Main.css
  src/member/Main.jsx
  src/parent/CardConsumeChartParent.jsx
  src/parent/CardHistoryParent.jsx
  src/parent/ChildEventSend.jsx
  src/parent/ParentMain.jsx
  src/quiz/QuizEnd.jsx
  src/quiz/QuizFailure.jsx
  src/quiz/QuizMain.jsx
  src/quiz/QuizQuiz.jsx
  src/quiz/QuizSuccess.jsx
  src/stock/StockBegin.jsx
  src/stock/StockHistory.jsx
  src/stock/StockHistoryDetail.jsx
  src/stock/StockStart.jsx
Labels: 🛠️ fix, 전운종

#113 [fix]: 메인페이지 포인트 추가 (#100)
  src/images/point/point01.jpg
  src/member/Main.css
  src/member/Main.jsx
Labels: 🛠️ fix, 강은영

#114 [fix] : Card 관련 화면 수정(#108)
  src/card/CardCreateSuccess.jsx
  src/card/CardHistory.jsx
  src/card/CardModifySuccess.jsx
  src/card/css/CardHistory.css
Labels: 🛠️ fix, 김용범

#116 [fix]: 출석체크 param으로 변경 (#115)
  src/daily/DailyMain.jsx
Labels: 🛠️ fix, 강은영

#117 [feat]: 투자 메인 페이지 개발
  src/stock/StockMain.jsx
  src/stock/StockStart.jsx
  src/stock/css/stockMain.css
Labels: ✅ feat, 박은수

#119 [fix]: front 요소 통일 및 로직 개선
  package-lock.json
  package.json
  src/account/AccountClose.jsx
  src/account/AccountDetail.jsx
  src/account/AccountInsert.jsx
  src/account/AccountMain.jsx
  src/account/css/AccountCreate.css
  src/account/css/AccountDetail.css
  src/account/css/AccountEnd.css
  src/account/css/AccountInsert.css
  src/card/CardConsumeChart.jsx
  src/card/CardHistory.jsx
  src/card/css/CardConsumeChart.css
  src/card/css/CardCreate.css
  src/card/css/CardCreateSuccess.css
  src/card/css/CardModify.css
  src/card/css/CardModifySuccess.css
  src/contract/ContractDetail.jsx
  src/daily/DailyMain.jsx
  src/daily/dailyEnd.css
  src/daily/dailyMain.css
  src/images/quiz.png
  src/member/Main.css
  src/member/Main.jsx
  src/moneyPlan/InputComponent.jsx
  src/moneyPlan/PlanChart.jsx
  src/moneyPlan/PlanComplete.jsx
  src/moneyPlan/PlanWrite.jsx
  src/moneyPlan/css/moneyPlan.css
  src/parent/CardHistoryParent.jsx
  src/parent/ParentAccount.jsx
  src/parent/css/CardConsumeChart.css
  src/parent/css/CardHistory.css
  src/quiz/QuizEnd.jsx
  src/quiz/QuizFailure.jsx
  src/quiz/QuizLoading.jsx
  src/quiz/QuizQuiz.jsx
  src/quiz/QuizSuccess.jsx
  src/quiz/css/quizEnd.css
  src/quiz/css/quizFailure.css
  src/quiz/css/quizMain.css
  src/quiz/css/quizQuiz.css
  src/quiz/css/quizSuccess.css
  src/stock/StockBegin.jsx
  src/stock/StockHistoryDetail.jsx
  src/stock/StockMain.jsx
  src/stock/StockStart.jsx
  src/stock/css/StockBegin.css
  src/stock/css/StockDetail.css
  src/stock/css/stockBuy.css
  src/stock/css/stockHistory.css
  src/stock/css/stockMain.css
  src/stock/css/stockRankDetail.css
  src/stock/css/stockRankResult.css
Labels: 🛠️ fix, 전운종

#121 [feat]: 내주식 손익 페이지 개발(#118)
  src/stock/MyStockProfit.jsx
  src/stock/StockMain.jsx
Labels: ✅ feat, 박은수

#125 [fix] : 소비패턴 용돈 내용 수정(#123)
  src/card/CardConsumeChart.jsx
  src/card/css/CardConsumeChart.css
Labels: 🛠️ fix, 김용범

#127 [fix]:용돈계획 날짜 내림차순 및 css 수정 (#124)
  src/images/deer/deer03.png
  src/moneyPlan/InputComponent.jsx
  src/moneyPlan/PlanChart.jsx
  src/moneyPlan/SelectChart.jsx
  src/moneyPlan/css/moneyPlan.css
Labels: 🛠️ fix, 정재윤

#130 [Fix]: 카드패턴 css 수정 / 주식 랭킹 히스토리 날짜 가공(#128)
  src/card/CardConsumeChart.jsx
  src/card/css/CardConsumeChart.css
  src/stock/StockHistory.jsx
Labels: 🛠️ fix, 정재윤

#132 [Fix]: 주식 / 마이페이지 css 수정 (#131)
  src/common/MyPage.jsx
  src/common/Mypage.css
  src/stock/StockMain.jsx
  src/stock/css/StockList.css
  src/stock/css/stockMain.css
Labels: 🛠️ fix, 정재윤

#135 [fix]: 주식 그래프 수정(#133)
  src/stock/StockDetail.jsx
Labels: 🛠️ fix, 박은수

#136 [Fix]: moneyPlan memberNum 수정 / stock css 수정 (#134)
  src/moneyPlan/PlanChart.jsx
  src/moneyPlan/PlanComplete.jsx
  src/moneyPlan/PlanWrite.jsx
  src/moneyPlan/SelectChart.jsx
  src/stock/StockHistory.jsx
  src/stock/css/stockHistoryDetail.css
Labels: 🛠️ fix, 정재윤

#137 [fix]: CSS 요소 개선
  src/card/CardHistory.jsx
  src/card/CardService.jsx
  src/card/css/CardHistory.css
  src/card/css/CardModify.css
  src/contract/ContractDetail.jsx
  src/contract/ContractDetailChild.jsx
  src/contract/ContractWrite.jsx
  src/contract/ContractWriteChild.jsx
  src/member/Main.css
  src/member/Main.jsx
  src/member/MyPage.jsx
  src/member/Mypage.css
  src/moneyPlan/PlanWrite.jsx
  src/moneyPlan/SelectChart.jsx
  src/parent/ChildEventSend.jsx
  src/router/MemberRouter.jsx
  src/stock/StockBuy.jsx
  src/stock/StockHistory.jsx
  src/stock/StockList.jsx
  src/stock/StockMain.jsx
  src/stock/StockStart.jsx
  src/stock/css/MyStockProfit.css
  src/stock/css/StockDetail.css
  src/stock/css/StockList.css
  src/stock/css/stockBuy.css
  src/stock/css/stockHistory.css
  src/stock/css/stockMain.css
Labels: 🛠️ fix, 전운종

#138 [fix]: 퀴즈 메인 의존성 배열 추가 (#120)
  src/quiz/QuizMain.jsx
Labels: 🛠️ fix, 강은영

#143 [fix]:font 변경(#139)
  src/App.css
  src/account/css/AccountCreate.css
  src/account/css/AccountDetail.css
  src/account/css/AccountEnd.css
  src/account/css/AccountInsert.css
  src/account/css/AccountMain.css
  src/contract/css/contractDetail.css
  src/contract/css/contractSelect.css
  src/contract/css/contractWrite.css
  src/contract/css/contractWriteChild.css
  src/contract/css/moneyContractManage.css
  src/member/Main.css
  src/member/Mypage.css
  src/member/login.css
  src/moneyPlan/css/moneyPlan.css
  src/parent/css/CardConsumeChart.css
  src/parent/css/CardHistory.css
  src/parent/css/childEventSend.css
  src/parent/css/parentMain.css
  src/quiz/css/quizFailure.css
  src/quiz/css/quizMain.css
  src/quiz/css/quizQuiz.css
  src/quiz/css/quizSuccess.css
  src/stock/css/CompanyInfo.css
  src/stock/css/StockBegin.css
  src/stock/css/StockDetail.css
  src/stock/css/StockInfoDetail.css
  src/stock/css/StockList.css
  src/stock/css/stockBuy.css
  src/stock/css/stockHistory.css
  src/stock/css/stockHistoryDetail.css
  src/stock/css/stockMain.css
  src/stock/css/stockModal.css
  src/stock/css/stockNews.css
  src/stock/css/stockRankDetail.css
  src/stock/css/stockRankResult.css
Labels: 🛠️ fix, 정재윤

#145 [fix]:의존성배열추가(#144)
  src/moneyPlan/SelectChart.jsx
Labels: 🛠️ fix, 정재윤

#142 [fix]: 매수, 매도 css 수정(#140)
  src/member/MyPage.jsx
  src/router/StockRouter.jsx
  src/stock/StockBuy.jsx
  src/stock/StockDetail.jsx
  src/stock/StockHistoryDetail.jsx
  src/stock/StockMain.jsx
  src/stock/StockSell.jsx
  src/stock/css/stockBuy.css
  src/stock/css/stockHistoryDetail.css
  src/stock/css/stockModal.css
Labels: 🛠️ fix, 박은수

#147 [fix]: 각종 오타 수정 및 저금통 기능 정상화
  src/account/AccountClose.jsx
  src/account/AccountEnd.jsx
  src/account/AccountInsert.jsx
  src/member/Main.jsx
  src/moneyPlan/SelectChart.jsx
  src/stock/StockBuy.jsx
  src/stock/StockSell.jsx
  src/stock/TradeDone.jsx
Labels: 🛠️ fix, 전운종

#153 [fix]: 저금통 도장 CSS 수정
  src/account/AccountDetail.jsx
  src/account/AccountMain.jsx
  src/account/css/AccountMain.css
Labels: 🛠️ fix, 전운종

#154 [fix]: 저금통 도장 CSS 수정
  src/account/AccountDetail.jsx
  src/account/AccountMain.jsx
  src/account/css/AccountMain.css
Labels: 🛠️ fix, 전운종

#155 [Fix]: 저금통 값 입력 천원 단위 가공 함수 추가( #149)
  src/account/AccountCreate.jsx
  src/account/AccountInsert.jsx
Labels: 🛠️ fix, 정재윤

#163 [fix]:color변경(#161)
  src/member/login.css
  src/stock/StockMain.jsx
  src/stock/css/MyStockProfit.css
  src/stock/css/StockDetail.css
  src/stock/css/StockList.css
  src/stock/css/stockBuy.css
  src/stock/css/stockHistoryDetail.css
  src/stock/css/stockMain.css
  src/stock/stockBuy.css
Labels: 🛠️ fix, 정재윤

#165 [fix]:부모페이지,pdf 수정(#129)
  src/common/FooterParent.jsx
  src/contract/ContractDetail.jsx
  src/contract/ContractSelect.jsx
  src/contract/ContractWrite.jsx
  src/contract/ContractWriteChild.jsx
  src/contract/MoneyContractManage.jsx
  src/contract/css/contractWriteChild.css
  src/contract/css/moneyContractManage.css
  src/parent/ChildEventSend.jsx
  src/parent/ParentMain.jsx
  src/parent/css/parentMain.css
Labels: 🛠️ fix, 김은정

#168 [fix]: 퀴즈, 출첵 css 수정, header 제목 굵기 수정 (#146)
  src/common/Header.css
  src/daily/DailyEnd.jsx
  src/daily/DailyMain.jsx
  src/daily/dailyEnd.css
  src/daily/dailyMain.css
  src/quiz/QuizEnd.jsx
  src/quiz/QuizMain.jsx
  src/quiz/css/quizEnd.css
  src/quiz/css/quizFailure.css
  src/quiz/css/quizLoading.css
  src/quiz/css/quizMain.css
  src/quiz/css/quizQuiz.css
  src/quiz/css/quizSuccess.css
  src/stock/StockHistory.jsx
Labels: 🛠️ fix, 강은영

#171 [Fix]:용돈계획 이미지 리사이징 / 금액 조회 수정(#166)
  src/moneyPlan/SelectChart.jsx
Labels: 🛠️ fix, 정재윤

#174 [fix]: css 수정 (#172)
  src/account/css/AccountMain.css
  src/card/css/CardHistory.css
  src/common/Footer.css
  src/contract/ContractSelect.jsx
  src/contract/ContractWrite.jsx
  src/contract/css/contractWrite.css
  src/parent/CardHistoryParent.jsx
  src/stock/css/StockDetail.css
  src/stock/css/stockMain.css
  src/stock/css/stockNews.css
Labels: 🛠️ fix, 박은수

#177 [Fix]주식페이지 스타일 수정(#175)
  src/card/css/CardCreate.css
  src/moneyPlan/SelectChart.jsx
  src/stock/MyStockProfit.jsx
  src/stock/StockBuy.jsx
  src/stock/StockDetail.jsx
  src/stock/StockList.jsx
  src/stock/StockSell.jsx
  src/stock/css/MyStockProfit.css
  src/stock/css/StockDetail.css
  src/stock/css/StockInfo.css
  src/stock/css/StockList.css
  src/stock/css/stockBuy.css
  src/stock/css/stockHistoryDetail.css
  src/stock/css/stockModal.css
  src/stock/css/stockNews.css
Labels: 🛠️ fix, 정재윤

#179 [Fix]:출첵 의존성 배열 추가 (#178)
  src/daily/DailyMain.jsx
  src/moneyPlan/SelectChart.jsx
Labels: 🛠️ fix, 정재윤

#180 [fix]:용돈보내기 알림기능 추가 (#167)
  src/contract/css/contractDetail.css
  src/contract/css/contractSelect.css
  src/parent/ChildEventSend.jsx
  src/parent/css/parentMain.css
Labels: 🛠️ fix, 김은정

#183 [fix]: 주식에대해 궁금해요 페이지 주제 보여주기(#182)
  src/stock/StockInfo.jsx
  src/stock/StockInfoDetail.jsx
Labels: 🛠️ fix, 박은수

#186 [fix]: minor fix
  src/card/css/CardCreate.css
  src/card/css/CardCreateSuccess.css
  src/card/css/CardModify.css
  src/card/css/CardModifySuccess.css
  src/common/Header.css
  src/daily/DailyMain.jsx
  src/member/Login.jsx
  src/member/Main.css
  src/member/Main.jsx
  src/member/MyPage.jsx
  src/member/Mypage.css
  src/member/SignUp.jsx
  src/member/login.css
  src/moneyPlan/SelectChart.jsx
  src/parent/ChildEventSend.jsx
  src/parent/ParentMain.jsx
  src/parent/css/parentMain.css
  src/quiz/css/quizFailure.css
  src/quiz/css/quizMain.css
  src/quiz/css/quizSuccess.css
  src/router/MemberRouter.jsx
  src/stock/StockHistory.jsx
  src/stock/StockInfo.jsx
  src/stock/StockList.jsx
  src/stock/StockMain.jsx
  src/stock/StockModal.jsx
  src/stock/css/StockBegin.css
  src/stock/css/StockDetail.css
  src/stock/css/StockList.css
  src/stock/css/stockHistory.css
  src/stock/css/stockHistoryDetail.css
  src/stock/css/stockMain.css
  src/stock/css/stockModal.css
Labels: 🛠️ fix, 전운종

#188 [Fix]:로그제거(#181)
  src/moneyPlan/SelectChart.jsx
  src/stock/StockBuy.jsx
  src/stock/StockMain.jsx
  src/stock/StockNews.jsx
  src/stock/StockRankDetail.jsx
  src/stock/StockSell.jsx
Labels: 🛠️ fix, 정재윤

#189 [Fix] 매도 관련 페이지 수정/#184
  src/stock/StockMain.jsx
  src/stock/StockSell.jsx
Labels: 🛠️ fix, 정홍택

#200 [fix]: 2차 QA 요구사항 반영
  src/account/AccountClose.jsx
  src/member/Main.jsx
  src/parent/ParentMain.jsx
  src/stock/MyStockProfit.jsx
  src/stock/StockInfo.jsx
  src/stock/StockSell.jsx
  src/stock/css/StockInfo.css
Labels: 🛠️ fix, 전운종

#203 [fix]: 부모 계약서 수정(#202)
  src/contract/ContractSelect.jsx
Labels: 🛠️ fix, 강은영

#206 [fix] 주식 장마감 시간 수정 /#204
  src/stock/StockMain.jsx
Labels: 🛠️ fix, 정홍택

#205 [fix]:asc정렬(#197)
  src/moneyPlan/PlanMain.jsx
  src/moneyPlan/SelectChart.jsx
  src/stock/StockMain.jsx
Labels: 🛠️ fix, 정재윤

#209 [hotfix]: 알림-저금통 조회 기능 정상화
  src/card/CardCreate.jsx
  src/card/CardCreateSuccess.jsx
  src/card/CardHistory.jsx
  src/member/Main.css
  src/member/Main.jsx
  src/parent/ParentAccount.jsx
Labels: 🔥 hotfix, 전운종
